var messages = new Object();
messages["Changing the file will reset this page."] = "Die Datei zu &auml;ndern, wird die Seite zur&uuml;cksetzen";
messages["Browser does not support HTTP Request"] = "Ihr Internetbetrachtungsprogramm (Browser) unterst&uuml;tzt kein HTTP Request, daher wird tdu nicht funktionieren.";
messages["Serverscipt returned error:\n"] = "Serverscript meldet Fehler:\n";
messages["New Search or scripting error => resetting Page."] = "Neue Suche gestartet oder Serverfehler => Neustart der Seite.";
messages["There is no Element to insert"] = "Kein Element zum Einf&uuml;gen";
messages["illegal graphic method (parameter sd)"] = "Illegale Grafikmethode (Parameter sd)";
messages["While calculating size summary: "] = "W&auml;hrend Gesamtgr&ouml;&szlig;enberechnung";
messages["Scripterror: line.length!=3 in Element "] = "Scriptfehler: line.length!=3 in Element ";
messages["Changing this setting will reset this page."] = "Das &Auml;ndern dieser Einstellung wird die Seite neustarten.";
