<?php
$messages = array (
  "Y-m-d H:i:s" => "d.m. H:i:s",
  "Pointererror" => "Zeigerfehler",
  "Error seeking file" => "Fehler bei seek() in Datei",
  "exiting" => "beende mich",
  "wrong parameter" => "falscher Parameter",
  "file open error" => "Datei&ouml;ffnenfehler",
  ", does it exist?" => ", existiert sie?",
  "wrong filetype" => "falscher Dateityp",
  ", no tdu file" => ", keine tdu-Datei",
  "Work in Progress" => "Scanner arbeitet noch",
  " does not exist or has no subdirs" => " existiert nicht oder hat keine Unterverzeichnisse",
  "select file to view" => "Aktuell angezeigte Datei",
  "select reference for graphic display" => "Referenz zur grafischen Anzeige",
  "Parent as reference" => "Elternverzeichnis als Referenz",
  "Total size as reference" => "Gesamtgr&ouml;&szlig;e als Referenz",
  "Biggest as reference" => "Gr&ouml;&szlig;tes als Referenz",
  "Entrys" => "Eintr&auml;ge",
  "starting time" => "Startzeit",
  "ending time" => "Endzeit",
  "runtime" => "Dauer",
  "Directory" => "Verzeichnis",
  "Size" => "Gr&ouml;&szlig;e",
  "Graphic" => "graphisch",
  "Scan still running, please wait..." => "Scanvorgang l&auml;uft, bitte warten...",
  "Warning: Changed File" => "Warnung: Scandatei gewechselt"
)
?>
